server:
  port: 8084
  address: 0.0.0.0
  servlet:
    context-path: /

spring:
    datasource:
        driver-class-name:  com.mysql.jdbc.Driver
        url: jdbc:mysql://23.83.229.159:3306/tcc_stock?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: root


mybatis:
  type-aliases-package: com.hmily.tcc.demo.dubbo.inventory.api.entity
  config-location: classpath:mybatis/mybatis-config.xml

logging:
    level:
        root: error
        org.springframework.web: info
        org.apache.ibatis: info
        org.dromara.hmily.bonuspoint: info
        org.dromara.hmily.lottery: info
        org.dromara.hmily: info
        io.netty: info
    path: "./logs"

