compensation:
   db:
      driver :  com.mysql.jdbc.Driver
      url: jdbc:mysql://23.83.229.159:3306/tcc?useUnicode=true&amp;characterEncoding=utf8&useSSL=false
      username: root
      password: root
